title: uxodb's blog 
description: >-
  IT enthusiast documenting his adventures in the technical realm.

lang: en-US
timezone: Europe/Amsterdam 
image: assets/favicons/android-chrome-192x192.png
repo: https://github.com/uxodb/klise-uxodb 
mode: dark

author:
  name: uxodb 
  bio: >-
    Recording my adventures in the technical realm...
  title: IT Engineer
  deco: 🤖
  username: uxodb
  github: uxodb
  avatar: /assets/img/avatar.webp

url: https://uxodb.me
baseurl:
permalink: /:title/
google_analytics: 
fb_appid:

collections:
  posts:
    output: true

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
    span:
      line_numbers: false


defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

number_of_posts: 5

sass:
  sourcemap: never
  style: compressed
  sass_dir: _sass

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles

